version: '3.8'
services:
  chat-service-db:
    image: mongo:6
    container_name: chat-service-db
    ports:
      - "27017:27017"
    volumes:
      - chat-service-db-data:/data/db
    networks:
        - shared-network

    chat-service:
      build:
        context: .
      container_name: chat-service
      ports:
        - "3005:3005"
      environment:
        AMQP_URL: amqp://user:password@rabbitmq:5672
        MONGO_URI:  mongodb://127.0.0.1:27017/talent_heaven
      depends_on:
        - chat-service-db
      networks:
          - shared-network

networks:
  shared-network:
    external: true

volumes:
    chat-service-db-data:
